# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cDUK2jB5wf4ZaWTANfsFzsjJa5aIHOrq

> # **DATASET OF EDX COURSES**

---

> # **TEAM MEMBERS**

**1.**   **Sanyam Bothra-E20CSE151**

**2.**   **Ishita Goyal-E20CSE153**

**3.**   **Sneha Gupta-E20CSE154**

> # **Step 1 - Select a real-world dataset**

**We have taken the dataset of edx courses till 2020.**

**The following are the analytic tasks we have performed:**

**TASK 1-What is the optimum course length of the courses?**

**TASK 2-How many courses provide Introductory, Intermediate and Advanced levels?**

**TASK 3-What is number of courses offered by each subject?**

**TASK 4-Which University is providing most courses?**

**TASK 5-What is the mean price offered by every subject?**

**TASK 6 - Which course length has the maximum enrollments?**

**TASK 7 - What is the number of enrollments in each level?**

**The working of this project is based on Pandas and various data visualization libraries of Python:**



**1.**   **Matplotlib**

**2.**   **Plotly**

**3. Seaborn**
"""

import pandas as pd
import io
import matplotlib.pyplot as plt
from collections import Counter
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib.pyplot as plt

edx=pd.read_csv("edx_courses.csv")          #To read the csv file and create a dataframe edx
edx

"""> # **Step 2 - Perform Data Preparation and Cleaning**

# **DATA CLEANING**
**We have loaded the dataset into data frame using Pandas. Our dataset is in the CSV format which has 975 rows x 16 columns.**

**We will be cleaning some of the columns from our orginal data:**

*   **course_description**
*   **course_syllabus**
*   **course_url**
*   **summary**
*   **language**
*   **subtitles**

**Also, we will be deleting some of the records which have null value and creating additional columns by splitting the original columns.**

**The above data cleaning will help in better understanding, clear data visualization and analysis.**
"""

edx.drop(["course_description","course_syllabus","course_url","summary","language","subtitles"],axis=1,inplace=True)   #Dropping the columns which are not required in analysis
edx['n_enrolled']=edx['n_enrolled'].str.replace(',','')                                                                #To remove ',' and replace it with blank space
edx.dropna(subset = ["n_enrolled"], inplace=True)                                                                      # Droping the NaN values from n_enrolled
edx=edx.reset_index(drop=True)                                                                                         #To reset the index of the table 
edx                                                                                                                    #calling dataframe to display

"""# **Splitting of price column**"""

z=edx['price'].str.split('FREE-Add a Verified Certificate for').str.get(1)      #To extract the $cost USD by using splitting at 'FREE-Add a Verified Certificate for'
z

edx['cost of verified certificate']=None                                        #Creating a new column and declaring it with none values for every row
index_description=edx.columns.get_loc('title')                                  # Taking reference of index from 'title' column
index_date=edx.columns.get_loc('cost of verified certificate')                  #To set the index of cost column accroding to 'title'
e=z.str.split('$')                                                              #To remove dollar from the entries in cost column
for i in range(0,855):
    t=(e[i][1])                                                                 #Creating a variable t and storing number+USD
    b=t.split()                                                                 #splitting t according to space and storing only numerical value in b
    edx.iat[i,index_date]=b[0]          
edx

"""# **Splitting of course_length column**"""

edx[['course_length', 'course_int']] = edx['course_length'].str.split(' ', 1, expand=True)    #To extract integer part from course length column
edx.drop(["course_int"],axis=1,inplace=True)                                                  #Dropping the course_int column as it is not required
edx

"""# **Implementing data through HEAT MAP**"""

dx=edx[['n_enrolled','cost of verified certificate','course_length']]           #creating a dataframe dx consisting of 'n_enrolled','cost of verified certificate','course_length'
corre = dx.astype('float64').corr()                                             #converting the datatype of elements from string to float
  
data_set = corre.corr()                                                         #calling function corr to create heat map    
colormap = sns.color_palette("Blues")                                           #Setting color to blue for heat map
ax = sns.heatmap(data_set, linewidth = 0.5, annot=True, cmap = colormap )       #Code to create a heat map
  
plt.title("Heat Map")                                                           #Giving title as "Heat Map"
plt.show()                                                                      #To show the map

"""# **NOTE**✍ 

✔ **Above heatmap is for analysing the correlation between different columns of a dataset:**

*   **n_enrolled**

*   **cost of verified certificate**

*   **course_length**

✔ **You can see a vertical line around the heatmap, this is a color bar. It clearly indicates that, for higher value, the color is dark and for lower value, the color is a lighter shade.**

✔ **Above chart is made using Seaborn.**

> # **Step 3 and 4 - Perform exploratory analysis and visualization. Ask and answer questions about data**

# **TASK 1 - What is the optimum course length of the courses?**
"""

edx['course_length']                                                                  #Displaying the course length of every row

"""# **Taking out mean course length**"""

l=[]                                                                            #declaring a list to store the value of course_length    
sum=0   
p=0
for i in edx["course_length"]:                                                  #loop to find total course course_length and appending it to list
    p+=1
    w=int(i)
    sum+=w
    l.append(i)
print(sum/p)                                                                    #printing the mean course_length

"""**The mean course length deduced is 6.85.**

# **Implementing data through BUBBLE CHART**
"""

g=edx['course_length']                                                          #Creating dataframe g storing course_length details
t=[]                                                                            #Creating empty list  
p=[]                                                                            
p.append(g)                                                                     #Storing values of dataframe to p list
for i in range(0,855):                                                            
    t.append(p[0][i])                                                           #Appending the course_length to t
l = t
l = Counter(l).most_common()                                                    #Storing the each week with their occurance in the list l
m1=[]                                                                           #Creating a list to store weeks
for i in range (0,len(l)):                                                    
    m1.append(l[i][0])                                                          #Appending weeks to m1

m2=[]                                                                           #creating list to store count of each week
for i in range (0,len(l)):
    m2.append(l[i][1])                                                          #Appending to m2

for i in range(0,len(m1)):                                                      
    m1[i]=m1[i]+" weeks"                                                        #Concating the number with weeks in m1
print(m1)    
print(m2)

fig = go.Figure(data=[go.Scatter( 
    x=m1, y=m2,
    mode='markers',
    marker=dict(
        color=[120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 190, 200, 205],                                   #Selecting colors for graph
        opacity=[0.6],
        size=[120, 115, 110, 105, 100, 95, 90 ,85, 80, 75 ,70, 65, 60, 55, 50, 45, 40, 35],showscale=True,                                   #Defining the size of each bubble in chart
    )
)])

fig.update_layout(
    title='Optimum course length of courses',                                      #title of the bubble chart
  yaxis=dict(                                                                   #Assigning attributes to Y axis
        title='Course Length',                                                  
        gridcolor='white',
        gridwidth=2,
    ),

    xaxis=dict(                                                                 #Assigning attributes to X axis
        title='Weeks',  
        gridcolor='white',
        gridwidth=4,
    ),
    paper_bgcolor='rgb(243, 243, 243)',                                         #Colors for the backgroungd bubble chart
    plot_bgcolor='rgb(243, 243, 243)',
)
fig.show()                                                                      #To display scatter bubble chart

"""# **NOTE**✍

✔  **Bubble chart is primarily used to depict and show relationships between numeric variables.**

✔ **In the bubble chart above, each bubble represents duration of weeks, its area is proportional to its count of course length.**

✔ **From the above bubble chart, the course length of 6 weeks has the most count which means many courses have the course length of 6 weeks and course length 17 weeks has the least count.**

✔ **Above chart is made using Plotly.**

# **TASK 2 - How many courses provide Introductory, Intermediate and Advanced levels?**
"""

t=[]                                                                          #List to store the introductory , intermediate and advanced course 
t1=[]                                                                         # List to store the count of introductory , intermediate and advanced level
t.append(edx['Level'].value_counts())
for i in range(0,3):
  t1.append(t[0][i])                                                          #appending list
print(t1)                                                                     # Print the list in which 0 index has number of introductory level , 1 index has number of intermediate level ,
                                                                              #  2 index has number of advanced level

"""# **Implementing data through RADAR CHART**"""

fig = go.Figure(data=go.Scatterpolar(r=t1, theta=['Introductory','Intermediate', 'Advanced'], fill='toself'))             #For making radar chart where r is the count and theta is the levels
fig.update_layout(polar=dict(radialaxis=dict(visible=True),),showlegend=True)                                             #For making the radial axis and scale
fig.show()                                                                                                                #To display radar chart

"""# **NOTE**✍

✔ **A radar chart is an informative visual tool in which multiple variables are compared on a two-dimensional plane. Axes emerge from a common central point and all the axes are equally distributed and uniformly drawn from each other.**

✔ **From the above radar chart, we can see that majority of the courses by edx are Introductory and the least are Advanced.**

✔ **Above chart is made using Plotly.**

# **TASK 3 -	What is number of courses offered by each subject?**

# **Implementing data through BAR GRAPH**
"""

bar_edx=edx['subject'].value_counts()
bar_edx.plot(kind='bar',figsize=(20,10), title="Number of courses offered by each subject", color=['#ee6055','#60d394','#aaf683','#ffd97d',
                                                                              '#ff70a6','#ff9770','#ffd670','#e9ff70','#b965e3',
                                                                              '#7fc8f8','#dcedff','#5aa9e6','#79addc','#ffc09f',
                                                                              '#ffee93','#fcf5c7','#adf7b6','#cad893','#b4decf',
                                                                              '#edc889','#ead793','#edb7a3','#bdb2ff','#9bf6ff',
                                                                              '#ffc6ff','#e0c9b7','#ffaf9d','#eac5d8','#ffa6c1'])        #code To make bar graph

      
plt.xlabel("Subjects")     #Declaring x axis as Subjects
plt.ylabel("Number of Courses")  #Declaring y axis as Number of courses

"""# **NOTE**✍

✔ **Bar graphs are used to compare things between different groups or to track changes over time.**

✔ **The above bar graph is a decreasing graph, we can see that the maximun courses are offered by Computer Science and least courses are offered by Ethics.**

✔ **Above chart is made using Matplotlib.**

# **TASK 4 - Which University is providing most courses?**

# **Implementing data through PIE CHART**
"""

x=edx['institution'].value_counts().head(15)
x.plot(kind='pie',figsize=(13,10), title="Number of courses provided by the University", autopct='%1.1f%%', shadow=True, startangle=0,                                        #To create a pie chart by declaring kind ,size and other attributes 
       explode = (0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), colors = ['#ee6055','#60d394','#aaf683','#ffd97d','#ff70a6','#ff9770','#ffd670',        
                                                                            '#e9ff70','#b965e3','#7fc8f8','#dcedff','#5aa9e6','#79addc','#ffc09f','#ffee93',                          
                                                                            '#fcf5c7','#adf7b6','#cad893','#b4decf','#edc889','#ead793','#edb7a3',
                                                                            '#bdb2ff','#9bf6ff','#ffc6ff','#e0c9b7','#ffaf9d','#eac5d8','#ffa6c1'])                           #Declaring color coding for pie chart

"""# **NOTE**✍

✔ **A Pie Chart is a circular statistical plot that can display only one series of data. The area of the chart is the total percentage of the given data.** 

✔ **We have taken top 15 universities and henceforth we can conclude that most of the courses are offered by Harvard University and the least by The University of Maryland, College Park-University System of Maryland.**

✔ **Above chart is made using Matplotlib.**

# **TASK 5-What is the Mean price offered by every subject?**
"""

l1=[]    #Declaring a list to store mean cost of different subjects

p2=edx[edx['subject']=='Computer Science']                                    #Creating a dataframe p2 of computer science
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame
 
l21=[]                                                                        #Creating a list 
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of computer Science and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list  
for x in l54:                                                                 #loop for the values in l54   
    l32.append(float(x))                                                      #To convert the integer values to float
l32                                             
sum=0                                                                         #To Find sum of all the cost of courses in computer science
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                                                     #To find mean of the cost 
l1.append(a)                                                                  #Appending mean of computer Science to l1
print(l1)                                                                     #To print list

p2=edx[edx['subject']=='Data Analysis & Statistics']                          #Creating a dataframe p2 of Data Analysis & Statistics
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame

l21=[]                                                                        #Creating a list
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of Data Analysis & Statistics and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list
for x in l54:                                                                 #loop for the values in l54
    l32.append(float(x))                                                      #To convert the integer values to float
l32
sum=0                                                                         #To Find sum of all the cost of courses in computer science
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                             #To find mean of the cost 
l1.append(a)                                                                  #Appending mean of Data Analysis & Statistics to l1
print(l1)                                                                     #To print list

p2=edx[edx['subject']=='Education & Teacher Training']                        #Creating a dataframe p2 of Education & Teacher Training
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame

l21=[]                                                                        #Creating a list 
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of Education & Teacher Training and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list 
for x in l54:                                                                 #loop for the values in l54  
    l32.append(float(x))                                                      #To convert the integer values to float
l32                                                                         
sum=0                                                                         #To Find sum of all the cost of courses in Education & Teacher Training
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                             #To find mean of the cost 
l1.append(a)                                                                  #Appending mean of Education & Teacher Training to l1
print(l1)                                                                     #To print list

p2=edx[edx['subject']=='Science']                                             #Creating a dataframe p2 of Science
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame

l21=[]                                                                        #Creating a list 
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of Science and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list 
for x in l54:                                                                 #loop for the values in l54  
    l32.append(float(x))                                                      #To convert the integer values to float
l32                                                                         
sum=0                                                                         #To Find sum of all the cost of courses in Science
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                             #To find mean of the cost 
l1.append(a)                                                                  #Appending mean of Science to l1
print(l1)                                                                     #To print list

p2=edx[edx['subject']=='History']                                             #Creating a dataframe p2 of History
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame

l21=[]                                                                        #Creating a list 
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of History and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list 
for x in l54:                                                                 #loop for the values in l54  
    l32.append(float(x))                                                      #To convert the integer values to float
l32                                                                         
sum=0                                                                         #To Find sum of all the cost of courses in History
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                             #To find mean of the cost 
l1.append(a)                                                                  #Appending mean of History to l1
print(l1)                                                                     #To print list

p2=edx[edx['subject']=='Biology & Life Sciences']                             #Creating a dataframe p2 of Biology & Life Sciences
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame

l21=[]                                                                        #Creating a list 
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of Biology & Life Sciences and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list 
for x in l54:                                                                 #loop for the values in l54  
    l32.append(float(x))                                                      #To convert the integer values to float
l32                                                                         
sum=0                                                                         #To Find sum of all the cost of courses in Biology & Life Sciences
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                             #To find mean of the cost 
l1.append(a)                                                                  #Appending mean of Biology & Life Sciences to l1
print(l1)                                                                     #To print list

p2=edx[edx['subject']=='Environmental Studies']                               #Creating a dataframe p2 of Environmental Studies
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame

l21=[]                                                                        #Creating a list 
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of Environmental Studies and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list 
for x in l54:                                                                 #loop for the values in l54  
    l32.append(float(x))                                                      #To convert the integer values to float
l32                                                                         
sum=0                                                                         #To Find sum of all the cost of courses in Environmental Studies
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                             #To find mean of the cost 
l1.append(a)                                                                  #Appending mean of Environmental Studies to l1
print(l1)                                                                     #To print list

p2=edx[edx['subject']=='Humanities']                                          #Creating a dataframe p2 of Humanities
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame

l21=[]                                                                        #Creating a list 
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of Humanities and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list 
for x in l54:                                                                 #loop for the values in l54  
    l32.append(float(x))                                                      #To convert the integer values to float
l32                                                                         
sum=0                                                                         #To Find sum of all the cost of courses in Humanities
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                             #To find mean of the cost 
l1.append(a)                                                                  #Appending mean of Humanities to l1
print(l1)                                                                     #To print list

p2=edx[edx['subject']=='Ethics']                                              #Creating a dataframe p2 of Ethics
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame

l21=[]                                                                        #Creating a list 
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of Ethics and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list 
for x in l54:                                                                 #loop for the values in l54  
    l32.append(float(x))                                                      #To convert the integer values to float
l32                                                                         
sum=0                                                                         #To Find sum of all the cost of courses in Ethics
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                             #To find mean of the cost 
l1.append(a)                                                                  #Appending mean of Ethics to l1
print(l1)                                                                     #To print list

p2=edx[edx['subject']=='Health & Safety']                                     #Creating a dataframe p2 of Health & Safety
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame

l21=[]                                                                        #Creating a list 
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of Health & Safety and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list 
for x in l54:                                                                 #loop for the values in l54  
    l32.append(float(x))                                                      #To convert the integer values to float
l32                                                                         
sum=0                                                                         #To Find sum of all the cost of courses in Health & Safety
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                             #To find mean of the cost 
l1.append(a)                                                                  #Appending mean of Health & Safety to l1
print(l1)                                                                     #To print list

p2=edx[edx['subject']=='Food & Nutrition']                                    #Creating a dataframe p2 of Food & Nutrition
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame

l21=[]                                                                        #Creating a list 
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of Food & Nutrition and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list 
for x in l54:                                                                 #loop for the values in l54  
    l32.append(float(x))                                                      #To convert the integer values to float
l32                                                                         
sum=0                                                                         #To Find sum of all the cost of courses in Food & Nutrition
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                             #To find mean of the cost 
l1.append(a)                                                                  #Appending mean of Food & Nutrition to l1
print(l1)                                                                     #To print list

p2=edx[edx['subject']=='Business & Management']                               #Creating a dataframe p2 of Business & Management
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame

l21=[]                                                                        #Creating a list 
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of Business & Management and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list 
for x in l54:                                                                 #loop for the values in l54  
    l32.append(float(x))                                                      #To convert the integer values to float
l32                                                                         
sum=0                                                                         #To Find sum of all the cost of courses in Business & Management
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                             #To find mean of the cost 
l1.append(a)                                                                  #Appending mean of Business & Management to l1
print(l1)                                                                     #To print list

p2=edx[edx['subject']=='Social Sciences']                                     #Creating a dataframe p2 of Social Sciences
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame

l21=[]                                                                        #Creating a list 
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of Social Sciences and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list 
for x in l54:                                                                 #loop for the values in l54  
    l32.append(float(x))                                                      #To convert the integer values to float
l32                                                                         
sum=0                                                                         #To Find sum of all the cost of courses in Social Sciences
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                             #To find mean of the cost 
l1.append(a)                                                                  #Appending mean of Social Sciences to l1
print(l1)                                                                     #To print list

l1  #Printing the list of mean of all subjects

"""# **Implementing data through DONUT CHART**"""

labels = ['Computer Science','Data Analysis & Statistics','Education & Teacher Training','Science','History',
          'Biology & Life Sciences','Environmental Studies','Humanities','Ethics','Health & Safety',
          'Food & Nutrition','Business & Management','Social Sciences']                                      #Declaring labels of the subjects for which we have calculated mean
values = l1                                                                                                  #Assigning values to l1
fig = go.Figure(data=[go.Pie(labels=labels, values=l1, hole=0.4)])                                           #Code create a donut chart
fig.update_layout(title_text="Mean price offered by each course", annotations=[dict(text='Mean', x=0.50, y=0.5, font_size=20, showarrow=False)]) #Add annotations in the center of the donut pies.
fig.show()                                                                                                                                             #Displaying the donut chart

"""# **NOTE**✍
✔ **Donut Charts are a special kind of Pie chart with the difference that it has a Blank Circle at the center. This empty space can be used to display additional data. It is used for displaying percentage data for categorical variables with a limited number of groups.**

✔ **The above donut chart indicates the mean price offered by each course in percentage.**

✔ **Above chart is made using Plotly.**

# **Implemented data through SCATTER PLOT**

(remaining data from the subjects)
"""

l2=[]                                                                          #Declaring a list to store mean cost of different subjects

p2=edx[edx['subject']=='Engineering']                                         #Creating a dataframe p2 of Engineering
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame

l21=[]                                                                        #Creating a list 
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of Engineering and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list 
for x in l54:                                                                 #loop for the values in l54  
    l32.append(float(x))                                                      #To convert the integer values to float
l32                                                                         
sum=0                                                                         #To Find sum of all the cost of courses in Engineering
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                             #To find mean of the cost 
l2.append(a)                                                                  #Appending mean of Engineering to l2
print(l2)

p2=edx[edx['subject']=='Economics & Finance']                                 #Creating a dataframe p2 of Economics & Finance
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame

l21=[]                                                                        #Creating a list 
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of Economics & Finance and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list 
for x in l54:                                                                 #loop for the values in l54  
    l32.append(float(x))                                                      #To convert the integer values to float
l32                                                                         
sum=0                                                                         #To Find sum of all the cost of courses in Economics & Finance
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                             #To find mean of the cost 
l2.append(a)                                                                  #Appending mean of Economics & Finance to l2
print(l2)

p2=edx[edx['subject']=='Communication']                                     #Creating a dataframe p2 of Communication
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame

l21=[]                                                                        #Creating a list 
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of Communication and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list 
for x in l54:                                                                 #loop for the values in l54  
    l32.append(float(x))                                                      #To convert the integer values to float
l32                                                                         
sum=0                                                                         #To Find sum of all the cost of courses in Communication
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                             #To find mean of the cost 
l2.append(a)                                                                  #Appending mean of Communication to l2
print(l2)

p2=edx[edx['subject']=='Language']                                            #Creating a dataframe p2 of Language
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame

l21=[]                                                                        #Creating a list 
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of Language and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list 
for x in l54:                                                                 #loop for the values in l54  
    l32.append(float(x))                                                      #To convert the integer values to float
l32                                                                         
sum=0                                                                         #To Find sum of all the cost of courses in Language
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                             #To find mean of the cost 
l2.append(a)                                                                  #Appending mean of Language to l2
print(l2)

p2=edx[edx['subject']=='Math']                                                #Creating a dataframe p2 of Math
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame

l21=[]                                                                        #Creating a list 
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of Math and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list 
for x in l54:                                                                 #loop for the values in l54  
    l32.append(float(x))                                                      #To convert the integer values to float
l32                                                                         
sum=0                                                                         #To Find sum of all the cost of courses in Math
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                             #To find mean of the cost 
l2.append(a)                                                                  #Appending mean of Math to l2
print(l2)

p2=edx[edx['subject']=='Medicine']                                            #Creating a dataframe p2 of Medicine
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame

l21=[]                                                                        #Creating a list 
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of Medicine and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list 
for x in l54:                                                                 #loop for the values in l54  
    l32.append(float(x))                                                      #To convert the integer values to float
l32                                                                         
sum=0                                                                         #To Find sum of all the cost of courses in Medicine
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                             #To find mean of the cost 
l2.append(a)                                                                  #Appending mean of Medicine to l2
print(l2)

p2=edx[edx['subject']=='Physics']                                     #Creating a dataframe p2 of Physics
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame

l21=[]                                                                        #Creating a list 
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of Physics and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list 
for x in l54:                                                                 #loop for the values in l54  
    l32.append(float(x))                                                      #To convert the integer values to float
l32                                                                         
sum=0                                                                         #To Find sum of all the cost of courses in Physics
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                             #To find mean of the cost 
l2.append(a)                                                                  #Appending mean of Physics to l2
print(l2)

p2=edx[edx['subject']=='Chemistry']                                     #Creating a dataframe p2 of Chemistry
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame

l21=[]                                                                        #Creating a list 
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of Chemistry and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list 
for x in l54:                                                                 #loop for the values in l54  
    l32.append(float(x))                                                      #To convert the integer values to float
l32                                                                         
sum=0                                                                         #To Find sum of all the cost of courses in Chemistry
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                             #To find mean of the cost 
l2.append(a)                                                                  #Appending mean of Chemistry to l2
print(l2)

p2=edx[edx['subject']=='Design']                                              #Creating a dataframe p2 of Design
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame

l21=[]                                                                        #Creating a list 
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of Design and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list 
for x in l54:                                                                 #loop for the values in l54  
    l32.append(float(x))                                                      #To convert the integer values to float
l32                                                                         
sum=0                                                                         #To Find sum of all the cost of courses in Design
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                             #To find mean of the cost 
l2.append(a)                                                                  #Appending mean of Design to l2
print(l2)

p2=edx[edx['subject']=='Music']                                               #Creating a dataframe p2 of Music
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame

l21=[]                                                                        #Creating a list 
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of Music and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list 
for x in l54:                                                                 #loop for the values in l54  
    l32.append(float(x))                                                      #To convert the integer values to float
l32                                                                         
sum=0                                                                         #To Find sum of all the cost of courses in Music
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                             #To find mean of the cost 
l2.append(a)                                                                  #Appending mean of Music to l2
print(l2)

p2=edx[edx['subject']=='Electronics']                                         #Creating a dataframe p2 of Electronics
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame

l21=[]                                                                        #Creating a list 
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of Electronics and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list 
for x in l54:                                                                 #loop for the values in l54  
    l32.append(float(x))                                                      #To convert the integer values to float
l32                                                                         
sum=0                                                                         #To Find sum of all the cost of courses in Electronics
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                             #To find mean of the cost 
l2.append(a)                                                                  #Appending mean of Electronics to l2
print(l2)

p2=edx[edx['subject']=='Energy & Earth Sciences']                             #Creating a dataframe p2 of Energy & Earth Sciences
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame

l21=[]                                                                        #Creating a list 
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of Energy & Earth Sciences and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list 
for x in l54:                                                                 #loop for the values in l54  
    l32.append(float(x))                                                      #To convert the integer values to float
l32                                                                         
sum=0                                                                         #To Find sum of all the cost of courses in Energy & Earth Sciences
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                             #To find mean of the cost 
l2.append(a)                                                                  #Appending mean of Energy & Earth Sciences to l2
print(l2)

p2=edx[edx['subject']=='Architecture']                                        #Creating a dataframe p2 of Architecture
p2=p2.reset_index(drop=True)                                                  #To Reset index in p2 frame

l21=[]                                                                        #Creating a list 
l21.append(p2['cost of verified certificate'])                                #appending l21 with the cost of Architecture and index

l54=[]                                                                        #Creating a list
for i in range(len(p2['cost of verified certificate'])):                      #To initialise a loop from zero till length of 'cost'
    l54.append(l21[0][i])                                                     #To append cost by dropping the index value
l32=[]                                                                        #Creating another list 
for x in l54:                                                                 #loop for the values in l54  
    l32.append(float(x))                                                      #To convert the integer values to float
l32                                                                         
sum=0                                                                         #To Find sum of all the cost of courses in Architecture
for i in l32:
    sum+=i                                                                    #Incrementing value of sum
a=(sum/(len(p2['cost of verified certificate'])))                             #To find mean of the cost 
l2.append(a)                                                                  #Appending mean of Architecture to l2
print(l2)

x=['Engineering','EF','Communication','Language','Math','Medicine',            #Declaring x.
          'Physics','Chemistry','Design','Music','Electronics',
          'EES','Architecture']
y=l2                                                                           #Declaring l2 list in y.
plt.figure(figsize=(18, 8))                                                    #Making the scatter plot.
plt.scatter(x, y, c ="yellow",
            linewidths = 1.5,
            marker ="*", 
            edgecolor ="green", 
            s = 300)

plt.xlabel("Subjects")                                                         #Label for x-axis.
plt.ylabel("Mean cost")  
plt.title("Mean price offered by each course")                                 #Label for y-aixs.

"""# **NOTE**✍

✔ **Scatter plots are used to observe relationship between variables and uses dots to represent the relationship between them.**

✔ **The above scatter plot indicates the mean price offered by each course.**

✔ **Above chart is made using Matplotlib.**

# **TASK 6 - Which course length has the maximum enrollments ?**
"""

p1=edx[edx['course_length']=='1']                                               #Creating a dataframe p1 of 1 weeks
p1=p1.reset_index(drop=True)                                                    #To Reset index in p1 frame
p1
l1=[]                                                                           #Creating a list l1
l1.append(p1['n_enrolled'])                                                     #appending l1 with the n_enrolled

 
l2=[]                                                                           #Creating a list l2
for i in range(len(p1['n_enrolled'])):                                          #To initialise a loop from zero till length of 'n_enrolled'
    l2.append(l1[0][i])                                                         #To append n_enrolled by dropping the index value
                                                                                                         
l3=[]                                                                           #Creating another list 
for x in l2:                                                                    #loop for the values in l3  
    l3.append(int(x)) 


sum=0                                                                           #To Find sum of all the n_enrolled.
for i in l3:
  sum=sum+i                                                                     #Incrementing value of sum
print(sum)                                                                      #Printing sum
lf=[]                                                                           #Final list
lf.append(sum)                                                                  #Appending in final list
print(lf)

p1=edx[edx['course_length']=='2']                                               #Creating a dataframe p1 of 2 weeks
p1=p1.reset_index(drop=True)                                                    #To Reset index in p1 frame
p1
l1=[]                                                                           #Creating a list l1
l1.append(p1['n_enrolled'])                                                     #appending l1 with the n_enrolled

 
l2=[]                                                                           #Creating a list l2
for i in range(len(p1['n_enrolled'])):                                          #To initialise a loop from zero till length of 'n_enrolled'
    l2.append(l1[0][i])                                                         #To append n_enrolled by dropping the index value
                                                                                                         
l3=[]                                                                           #Creating another list 
for x in l2:                                                                    #loop for the values in l3  
    l3.append(int(x)) 


sum=0                                                                           #To Find sum of all the n_enrolled.
for i in l3:
  sum=sum+i                                                                     #Incrementing value of sum
print(sum)                                                                      #Printing sum
                                                                          
lf.append(sum)                                                                  #Appending in final list
print(lf)

p1=edx[edx['course_length']=='3']                                               #Creating a dataframe p1 of 3 weeks
p1=p1.reset_index(drop=True)                                                    #To Reset index in p1 frame
p1
l1=[]                                                                           #Creating a list l1
l1.append(p1['n_enrolled'])                                                     #appending l1 with the n_enrolled

 
l2=[]                                                                           #Creating a list l2
for i in range(len(p1['n_enrolled'])):                                          #To initialise a loop from zero till length of 'n_enrolled'
    l2.append(l1[0][i])                                                         #To append n_enrolled by dropping the index value
                                                                                                         
l3=[]                                                                           #Creating another list 
for x in l2:                                                                    #loop for the values in l3  
    l3.append(int(x)) 


sum=0                                                                           #To Find sum of all the n_enrolled.
for i in l3:
  sum=sum+i                                                                     #Incrementing value of sum
print(sum)                                                                      #Printing sum
lf.append(sum)                                                                  #Appending in final list
print(lf)

p1=edx[edx['course_length']=='4']                                               #Creating a dataframe p1 of 4 weeks
p1=p1.reset_index(drop=True)                                                    #To Reset index in p1 frame
p1
l1=[]                                                                           #Creating a list l1
l1.append(p1['n_enrolled'])                                                     #appending l1 with the n_enrolled

 
l2=[]                                                                           #Creating a list l2
for i in range(len(p1['n_enrolled'])):                                          #To initialise a loop from zero till length of 'n_enrolled'
    l2.append(l1[0][i])                                                         #To append n_enrolled by dropping the index value
                                                                                                         
l3=[]                                                                           #Creating another list 
for x in l2:                                                                    #loop for the values in l3  
    l3.append(int(x)) 


sum=0                                                                           #To Find sum of all the n_enrolled.
for i in l3:
  sum=sum+i                                                                     #Incrementing value of sum
print(sum)                                                                      #Printing sum
lf.append(sum)                                                                  #Appending in final list
print(lf)

p1=edx[edx['course_length']=='5']                                               #Creating a dataframe p1 of 5 weeks
p1=p1.reset_index(drop=True)                                                    #To Reset index in p1 frame
p1
l1=[]                                                                           #Creating a list l1
l1.append(p1['n_enrolled'])                                                     #appending l1 with the n_enrolled

 
l2=[]                                                                           #Creating a list l2
for i in range(len(p1['n_enrolled'])):                                          #To initialise a loop from zero till length of 'n_enrolled'
    l2.append(l1[0][i])                                                         #To append n_enrolled by dropping the index value
                                                                                                         
l3=[]                                                                           #Creating another list 
for x in l2:                                                                    #loop for the values in l3  
    l3.append(int(x)) 


sum=0                                                                           #To Find sum of all the n_enrolled.
for i in l3:
  sum=sum+i                                                                     #Incrementing value of sum
print(sum)                                                                      #Printing sum
lf.append(sum)                                                                  #Appending in final list
print(lf)

p1=edx[edx['course_length']=='6']                                               #Creating a dataframe p1 of 6 weeks
p1=p1.reset_index(drop=True)                                                    #To Reset index in p1 frame
p1
l1=[]                                                                           #Creating a list l1
l1.append(p1['n_enrolled'])                                                     #appending l1 with the n_enrolled

 
l2=[]                                                                           #Creating a list l2
for i in range(len(p1['n_enrolled'])):                                          #To initialise a loop from zero till length of 'n_enrolled'
    l2.append(l1[0][i])                                                         #To append n_enrolled by dropping the index value
                                                                                                         
l3=[]                                                                           #Creating another list 
for x in l2:                                                                    #loop for the values in l3  
    l3.append(int(x)) 


sum=0                                                                           #To Find sum of all the n_enrolled.
for i in l3:
  sum=sum+i                                                                     #Incrementing value of sum
print(sum)                                                                      #Printing sum
lf.append(sum)                                                                  #Appending in final list
print(lf)

p1=edx[edx['course_length']=='7']                                               #Creating a dataframe p1 of 7 weeks
p1=p1.reset_index(drop=True)                                                    #To Reset index in p1 frame
p1
l1=[]                                                                           #Creating a list l1
l1.append(p1['n_enrolled'])                                                     #appending l1 with the n_enrolled

 
l2=[]                                                                           #Creating a list l2
for i in range(len(p1['n_enrolled'])):                                          #To initialise a loop from zero till length of 'n_enrolled'
    l2.append(l1[0][i])                                                         #To append n_enrolled by dropping the index value
                                                                                                         
l3=[]                                                                           #Creating another list 
for x in l2:                                                                    #loop for the values in l3  
    l3.append(int(x)) 


sum=0                                                                           #To Find sum of all the n_enrolled.
for i in l3:
  sum=sum+i                                                                     #Incrementing value of sum
print(sum)                                                                      #Printing sum
lf.append(sum)                                                                  #Appending in final list
print(lf)

p1=edx[edx['course_length']=='8']                                               #Creating a dataframe p1 of 8 weeks
p1=p1.reset_index(drop=True)                                                    #To Reset index in p1 frame
p1
l1=[]                                                                           #Creating a list l1
l1.append(p1['n_enrolled'])                                                     #appending l1 with the n_enrolled

 
l2=[]                                                                           #Creating a list l2
for i in range(len(p1['n_enrolled'])):                                          #To initialise a loop from zero till length of 'n_enrolled'
    l2.append(l1[0][i])                                                         #To append n_enrolled by dropping the index value
                                                                                                         
l3=[]                                                                           #Creating another list 
for x in l2:                                                                    #loop for the values in l3  
    l3.append(int(x)) 


sum=0                                                                           #To Find sum of all the n_enrolled.
for i in l3:
  sum=sum+i                                                                     #Incrementing value of sum
print(sum)                                                                      #Printing sum
lf.append(sum)                                                                  #Appending in final list
print(lf)

p1=edx[edx['course_length']=='9']                                               #Creating a dataframe p1 of 9 weeks
p1=p1.reset_index(drop=True)                                                    #To Reset index in p1 frame
p1
l1=[]                                                                           #Creating a list l1
l1.append(p1['n_enrolled'])                                                     #appending l1 with the n_enrolled

 
l2=[]                                                                           #Creating a list l2
for i in range(len(p1['n_enrolled'])):                                          #To initialise a loop from zero till length of 'n_enrolled'
    l2.append(l1[0][i])                                                         #To append n_enrolled by dropping the index value
                                                                                                         
l3=[]                                                                           #Creating another list 
for x in l2:                                                                    #loop for the values in l3  
    l3.append(int(x)) 


sum=0                                                                           #To Find sum of all the n_enrolled.
for i in l3:
  sum=sum+i                                                                     #Incrementing value of sum
print(sum)                                                                      #Printing sum
lf.append(sum)                                                                  #Appending in final list
print(lf)

p1=edx[edx['course_length']=='10']                                               #Creating a dataframe p1 of 10 weeks
p1=p1.reset_index(drop=True)                                                    #To Reset index in p1 frame
p1
l1=[]                                                                           #Creating a list l1
l1.append(p1['n_enrolled'])                                                     #appending l1 with the n_enrolled

 
l2=[]                                                                           #Creating a list l2
for i in range(len(p1['n_enrolled'])):                                          #To initialise a loop from zero till length of 'n_enrolled'
    l2.append(l1[0][i])                                                         #To append n_enrolled by dropping the index value
                                                                                                         
l3=[]                                                                           #Creating another list 
for x in l2:                                                                    #loop for the values in l3  
    l3.append(int(x)) 


sum=0                                                                           #To Find sum of all the n_enrolled.
for i in l3:
  sum=sum+i                                                                     #Incrementing value of sum
print(sum)                                                                      #Printing sum
lf.append(sum)                                                                  #Appending in final list
print(lf)

p1=edx[edx['course_length']=='11']                                               #Creating a dataframe p1 of 11 weeks
p1=p1.reset_index(drop=True)                                                    #To Reset index in p1 frame
p1
l1=[]                                                                           #Creating a list l1
l1.append(p1['n_enrolled'])                                                     #appending l1 with the n_enrolled

 
l2=[]                                                                           #Creating a list l2
for i in range(len(p1['n_enrolled'])):                                          #To initialise a loop from zero till length of 'n_enrolled'
    l2.append(l1[0][i])                                                         #To append n_enrolled by dropping the index value
                                                                                                         
l3=[]                                                                           #Creating another list 
for x in l2:                                                                    #loop for the values in l3  
    l3.append(int(x)) 


sum=0                                                                           #To Find sum of all the n_enrolled.
for i in l3:
  sum=sum+i                                                                     #Incrementing value of sum
print(sum)                                                                      #Printing sum
lf.append(sum)                                                                  #Appending in final list
print(lf)

p1=edx[edx['course_length']=='12']                                               #Creating a dataframe p1 of 12 weeks
p1=p1.reset_index(drop=True)                                                    #To Reset index in p1 frame
p1
l1=[]                                                                           #Creating a list l1
l1.append(p1['n_enrolled'])                                                     #appending l1 with the n_enrolled

 
l2=[]                                                                           #Creating a list l2
for i in range(len(p1['n_enrolled'])):                                          #To initialise a loop from zero till length of 'n_enrolled'
    l2.append(l1[0][i])                                                         #To append n_enrolled by dropping the index value
                                                                                                         
l3=[]                                                                           #Creating another list 
for x in l2:                                                                    #loop for the values in l3  
    l3.append(int(x)) 


sum=0                                                                           #To Find sum of all the n_enrolled.
for i in l3:
  sum=sum+i                                                                     #Incrementing value of sum
print(sum)                                                                      #Printing sum
lf.append(sum)                                                                  #Appending in final list
print(lf)

p1=edx[edx['course_length']=='13']                                               #Creating a dataframe p1 of 13 weeks
p1=p1.reset_index(drop=True)                                                    #To Reset index in p1 frame
p1
l1=[]                                                                           #Creating a list l1
l1.append(p1['n_enrolled'])                                                     #appending l1 with the n_enrolled

 
l2=[]                                                                           #Creating a list l2
for i in range(len(p1['n_enrolled'])):                                          #To initialise a loop from zero till length of 'n_enrolled'
    l2.append(l1[0][i])                                                         #To append n_enrolled by dropping the index value
                                                                                                         
l3=[]                                                                           #Creating another list 
for x in l2:                                                                    #loop for the values in l3  
    l3.append(int(x)) 


sum=0                                                                           #To Find sum of all the n_enrolled.
for i in l3:
  sum=sum+i                                                                     #Incrementing value of sum
print(sum)                                                                      #Printing sum
lf.append(sum)                                                                  #Appending in final list
print(lf)

p1=edx[edx['course_length']=='14']                                               #Creating a dataframe p1 of 14 weeks
p1=p1.reset_index(drop=True)                                                    #To Reset index in p1 frame
p1
l1=[]                                                                           #Creating a list l1
l1.append(p1['n_enrolled'])                                                     #appending l1 with the n_enrolled

 
l2=[]                                                                           #Creating a list l2
for i in range(len(p1['n_enrolled'])):                                          #To initialise a loop from zero till length of 'n_enrolled'
    l2.append(l1[0][i])                                                         #To append n_enrolled by dropping the index value
                                                                                                         
l3=[]                                                                           #Creating another list 
for x in l2:                                                                    #loop for the values in l3  
    l3.append(int(x)) 


sum=0                                                                           #To Find sum of all the n_enrolled.
for i in l3:
  sum=sum+i                                                                     #Incrementing value of sum
print(sum)                                                                      #Printing sum
lf.append(sum)                                                                  #Appending in final list
print(lf)

p1=edx[edx['course_length']=='15']                                               #Creating a dataframe p1 of 15 weeks
p1=p1.reset_index(drop=True)                                                    #To Reset index in p1 frame
p1
l1=[]                                                                           #Creating a list l1
l1.append(p1['n_enrolled'])                                                     #appending l1 with the n_enrolled

 
l2=[]                                                                           #Creating a list l2
for i in range(len(p1['n_enrolled'])):                                          #To initialise a loop from zero till length of 'n_enrolled'
    l2.append(l1[0][i])                                                         #To append n_enrolled by dropping the index value
                                                                                                         
l3=[]                                                                           #Creating another list 
for x in l2:                                                                    #loop for the values in l3  
    l3.append(int(x)) 


sum=0                                                                           #To Find sum of all the n_enrolled.
for i in l3:
  sum=sum+i                                                                     #Incrementing value of sum
print(sum)                                                                      #Printing sum
lf.append(sum)                                                                  #Appending in final list
print(lf)

p1=edx[edx['course_length']=='16']                                               #Creating a dataframe p1 of 16 weeks
p1=p1.reset_index(drop=True)                                                    #To Reset index in p1 frame
p1
l1=[]                                                                           #Creating a list l1
l1.append(p1['n_enrolled'])                                                     #appending l1 with the n_enrolled

 
l2=[]                                                                           #Creating a list l2
for i in range(len(p1['n_enrolled'])):                                          #To initialise a loop from zero till length of 'n_enrolled'
    l2.append(l1[0][i])                                                         #To append n_enrolled by dropping the index value
                                                                                                         
l3=[]                                                                           #Creating another list 
for x in l2:                                                                    #loop for the values in l3  
    l3.append(int(x)) 


sum=0                                                                           #To Find sum of all the n_enrolled.
for i in l3:
  sum=sum+i                                                                     #Incrementing value of sum
print(sum)                                                                      #Printing sum
lf.append(sum)                                                                  #Appending in final list
print(lf)

p1=edx[edx['course_length']=='17']                                               #Creating a dataframe p1 of 17 weeks
p1=p1.reset_index(drop=True)                                                    #To Reset index in p1 frame
p1
l1=[]                                                                           #Creating a list l1
l1.append(p1['n_enrolled'])                                                     #appending l1 with the n_enrolled

 
l2=[]                                                                           #Creating a list l2
for i in range(len(p1['n_enrolled'])):                                          #To initialise a loop from zero till length of 'n_enrolled'
    l2.append(l1[0][i])                                                         #To append n_enrolled by dropping the index value
                                                                                                         
l3=[]                                                                           #Creating another list 
for x in l2:                                                                    #loop for the values in l3  
    l3.append(int(x)) 


sum=0                                                                           #To Find sum of all the n_enrolled.
for i in l3:
  sum=sum+i                                                                     #Incrementing value of sum
print(sum)                                                                      #Printing sum
lf.append(sum)                                                                  #Appending in final list
print(lf)

p1=edx[edx['course_length']=='18']                                               #Creating a dataframe p1 of 18 weeks
p1=p1.reset_index(drop=True)                                                    #To Reset index in p1 frame
p1
l1=[]                                                                           #Creating a list l1
l1.append(p1['n_enrolled'])                                                     #appending l1 with the n_enrolled

l2=[]                                                                           #Creating a list l2
for i in range(len(p1['n_enrolled'])):                                          #To initialise a loop from zero till length of 'n_enrolled'
    l2.append(l1[0][i])  
                                                                                #To append n_enrolled by dropping the index value
                                                                                                         
l3=[]                                                                           #Creating another list 
for x in l2:                                                                    #loop for the values in l3  
    l3.append(int(x)) 


sum=0                                                                           #To Find sum of all the n_enrolled.
for i in l3:
  sum=sum+i                                                                     #Incrementing value of sum
print(sum)                                                                      #Printing sum
lf.append(sum)                                                                  #Appending in final list
print(lf)

fig = go.Figure(data=[go.Scatter( 
    x=['1 week','2 weeks','3 weeks','4 weeks','5 weeks','6 weeks','7 weeks','8 weeks','9 weeks',
    '10 weeks','11 weeks','12 weeks','13 weeks','14 weeks','15 weeks','16 weeks','17 weeks','18 weeks']
    , y=lf,
    mode='markers',
    marker=dict(
        color=[200, 205, 210, 215, 220, 225, 230, 235, 240, 245, 250 ,255, 260, 265, 270 ,275, 280, 285, 290 ,295, 300],                                   #Selecting colors for graph
        opacity=[0.6],
        size=[50, 40, 43, 50, 20, 56, 46 ,55, 30, 47 ,54 , 65, 30, 58, 50, 45, 40, 35],showscale=True,                                   #Defining the size of each bubble in chart
    )
)])

fig.update_layout(
    title='Course length having maximum enrollments ',                                      #title of the bubble chart
  yaxis=dict(                                                                   #Assigning attributes to Y axis
        title='Number of enrollments',                                                  
        gridcolor='white',
        gridwidth=2,
    ),

    xaxis=dict(                                                                 #Assigning attributes to X axis
        title='Weeks',  
        gridcolor='white',
        gridwidth=4,
    ),
    paper_bgcolor='rgb(243, 243, 243)',                                         #Colors for the backgroungd bubble chart
    plot_bgcolor='rgb(243, 243, 243)',
)
fig.show()

"""# **NOTE**✍

✔ **From the above graph, 6 weeks course has the maximum enrollments.**

✔ **Above chart is made using Plotly.**

# **TASK 7 - What is the number of enrollments in each level?**
"""

p=[]                                                                            
e=edx['Level']                                                                  #Creating a dataframe of e which has level column
l=[]                                                                              
p.append(e)                                                                     #appending p with the column value 
for i in range(0,855):
    
    l.append(p[0][i])                                                           #Storing introductory , intermediate , advance course
p=[]
e=edx['n_enrolled']                                                             #Storing n_enrolled in e dataframe
l1=[]
p.append(e)                                                                     #appending e to p
var=0
for i in range(0,855):


  l1.append(p[0][i])
integer_map = map(int, l1)
l1 = list(integer_map)
sumintro=0
sumintermediate=0
sumadvanced=0

for i in range(0,855):
    if(l[i]=='Introductory'):
        sumintro+=l1[i]
    elif(l[i]=='Intermediate'):
        sumintermediate+=l1[i]
    else:
        sumadvanced+=l1[i]
print(sumintro)
print(sumintermediate)
print(sumadvanced)

lf1=[]
lf1.append(sumintro)
lf1.append(sumintermediate)
lf1.append(sumadvanced)
print(lf1)

labels = ['Introductory','Intermediate', 'Advanced']                                                          #Declaring labels of the subjects for which we have calculated mean
values = lf1                                                                                                  #Assigning values to lf1
colors = ['#ff9770', '#ffd670', '#e9ff70']                                                                    
fig = go.Figure(data=[go.Pie(labels=labels, values=lf1)])                                                     #Code create a pie chart
fig.update_traces(hoverinfo='label+percent', textinfo='percent', textfont_size=20, marker=dict(colors=colors))    
fig.update_layout(title_text="Number of enrollments in each level")            
fig.show()

"""# **NOTE**✍

✔ **From the above graph, we can conclude that Introductory level has the maximum enrollments.**

✔  **Above chart is made using Plotly.**

> # **Step 5 - Summarize your inference and write a conclusion**

# **SUMMARY**

**In this mini project of Data Visualization and Analysis, we have learnt the use of Pandas which is a software library of Python used for data manipulation and analysis.**

**For Data Visualization we have used Matplotlib, Plotly and Seaborn, which are Python plotting libraries covering wide range of charts and graphs. The following types of graph has been used:**




*   **Heat Map**
*   **Radar Chart**

*   **Bar Graph**
*   **Pie Chart**

*   **Bubble Chart**
*   **Donut Chart**

*   **Scatter Plot**


**We selected a dataset of edx courses from Kaggle and performed data cleaning, analysis, and visualization of certain questions and performed some basic function like calculating sum, mean, count, splitting and appending items in list.**

# **CONCLUSION**

**We were able to acheive the appropriate results of the tasks and were able to compute all the basic functions in the project by using Pandas, Matplotplib, Plotly and Seaborn.**

# **FUTURE WORK**



**1.   Using different types of data visualization for handling large data.**

**2.  We will try to filter out the best courses in every subjects.**

**3. Trying to merge two set of data columns in one graph.**

**4. Making the graphs into 3D visuals.**

**5. We will try to add more interesting questions.**

# **LINKS**
https://www.kaggle.com/datasets?fileType=csv

https://jovian.ml/forum/t/recommended-datasets-for-course-project/11711

https://www.geeksforgeeks.org/python-pandas-dataframe/

https://www.edureka.co/blog/python-matplotlib-tutorial/

https://plotly.com/python/pie-charts/

https://www.geeksforgeeks.org/seaborn-heatmap-a-comprehensive-guide/

**Submitted by:-**

**Sanyam Bothra-E20CSE151**

**Ishita Goyal-E20CSE153**

**Sneha Gupta-E20CSE154**
"""